// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ToDoMVC_001 {
  private WebDriver driver;
  // private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    // vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void initialTest001() {
    driver.get("http://todomvc.com/examples/angularjs");
    driver.manage().window().setSize(new Dimension(640, 480));
    js.executeScript("window.scrollTo(0,487)");
    driver.findElement(By.cssSelector(".new-todo")).click();
    driver.findElement(By.cssSelector(".new-todo")).click();
    driver.findElement(By.cssSelector(".new-todo")).sendKeys("Drink water every hour.");
    driver.findElement(By.cssSelector(".new-todo")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".toggle")).click();
    driver.findElement(By.linkText("Completed")).click();
    driver.findElement(By.linkText("Active")).click();
    driver.findElement(By.linkText("Completed")).click();
    {
      WebElement element = driver.findElement(By.linkText("Completed"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("All")).click();
    driver.findElement(By.cssSelector(".new-todo")).click();
    driver.findElement(By.cssSelector(".new-todo")).sendKeys("A new item that will be deleted!");
    driver.findElement(By.cssSelector(".new-todo")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > .view > .destroy")).click();
    driver.findElement(By.linkText("Active")).click();
    driver.findElement(By.linkText("Completed")).click();
    {
      WebElement element = driver.findElement(By.linkText("Completed"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("All")).click();
  }
}
